name: dally
description: Dally Project

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management & routing tool
  get: ^4.6.1

  # http client
  retrofit: ^3.0.1+1
  logger: any
  http: ^0.13.4 # multipart support on web

  # storage
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  # svg
  flutter_svg: ^1.0.3

  # lottie
  lottie: ^1.2.2

  # image
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.6
  screenshot: ^1.2.3

  # date_format
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  retrofit_generator: ^4.0.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/

  fonts:
    - family: spoqa
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Thin.ttf
          weight: 200
        - asset: assets/fonts/SpoqaHanSansNeo-Light.ttf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.ttf
          weight: 700
